### ISSUE TITLE
Pre-Sea Grant checklist

### ISSUE THREAD

**Issue by DanOvando** [DanOvando/scrooge#16]
- [x] Check for bugs in length to age key

- [x] Check for bugs in selectivity

- [x] Add in profit per unit effort data and estimation

- [x] Set prior on sigma effort based on CV of F in RAM

- [x] Test server run Tuesday evening

- [x] Start full run by COB Wednesday

- [x] Presentation template done by COB Thursday

- [x] Integrate model runs Friday

- [x] Cross fingers

**Comment by DanOvando** [comment]
- [ ] add CI coverage diagnostics
