### ISSUE TITLE
pre-chapter checklist

### ISSUE THREAD

**Issue by DanOvando** [DanOvando/scrooge#20]

**Comment by DanOvando** [comment]
- [ ] keep track of q in prepare scrooge data
- [ ] make easier to specify what data you want to include in the assessment (e.g. just q)
- [ ] explore making more responsive to profit and q
